version: "3.8"

services:
  vpm:
    image: vagas-pra-mim
    container_name: vpm
    volumes:
      - ./:/vpm
      - /dev/shm:/dev/shm
    ports:
      - 5000:5001
    working_dir: /
    environment:
       HASH: dev

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - vpm-data:/var/lib/pgsql
    environment:
      POSTGRES_PASSWORD: postgresql

volumes:
  vpm-data:
