version: "3.9.16"

services:
  vpm:
    image: vagas-pra-mim
    container_name: vagas-pra-mim
    volumes:
      - /dev/shm:/dev/shm
      - .:/webapp
    ports:
      - 5000:5001
    depends_on:
      - db
    working_dir: /webapp
    environment:
      HASH: dev

  db:
    image: postgres
    container_name: postgres
    volumes:
      - vpm-data:/var/lib/pgsql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgresql

volumes:
  vpm-data:
