version: "3.8"

services:
  vpm:
    build: .
    container_name: vpm
    volumes:
      - ./:/vpm
      - /dev/shm:/dev/shm
    ports:
      - 5000:5000
    working_dir: /

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - vpm-data:/var/lib/pgsql
    environment:
      POSTGRES_PASSWORD: postgresql

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80

volumes:
  vpm-data:
